packages:
  - scripts/*
  - config/*
  - packages/*
# 定义目录和依赖版本号
catalog:
  "@changesets/cli": ^2.29.5
  "@commitlint/cli": ^19.2.1
  "@commitlint/config-conventional": ^19.1.0
  "@formily/antd-v5": ^1.2.4
  "@formily/core": ^2.3.7
  "@formily/react": ^2.3.7
  "@koa/bodyparser": ^6.0.0
  "@rsbuild/core": ^1.3.22
  "@rsbuild/plugin-less": ^1.2.5
  "@rsbuild/plugin-react": ^1.3.2
  "@rsbuild/plugin-vue": ^1.1.0
  "@tailwindcss/postcss": ^4.1.11
  "@types/koa": ^2.15.0
  "@types/koa-static": ^4.0.4
  "@types/node": ^24.0.12
  "@types/react": ^19.1.0
  "@types/react-dom": ^19.1.0
  antd: ^5.26.4
  axios: ^1.10.0
  chalk: ^5.4.1
  cross-env: ^7.0.3
  dotenv: ^17.2.0
  dotenv-cli: ^8.0.0
  husky: ^9.0.11
  koa: ^3.0.0
  koa-proxies: ^0.12.4
  koa-static: ^5.0.0
  lint-staged: ^15.2.2
  moment: ^2.30.1
  react: ^19.1.0
  react-dom: ^19.1.0
  react-router-dom: ^7.6.2
  tailwindcss: ^4.1.11
  tsup: ^8.5.0
  tsx: ^4.20.3
  turbo: ^2.5.4
  typescript: ^5.4.2
